### ISSUE TITLE
Hey i cant reach you on other ways

### ISSUE THREAD

**Issue by Shiemy** [xan105/Aion-Japanese-Voice-Pack#1]
The Aion launcher dont update the Japanese Voice anymore it tells me alsways something is wrong, please write the Owner, but you Archived the Aion Launcher sadly :( i loved your work, so can you pls tell me how to download the newest japanese sounds?
or how to fix the launcher?

**Comment by xan105** [comment]
What does the log have to say ? -> %AppData%\Local\AION-LIVE\log\aion.log
